CREATE TABLE jackpots
(
    id                         VARCHAR(36) PRIMARY KEY,
    initial_pool               DECIMAL(19, 2) NOT NULL,
    current_pool               DECIMAL(19, 2) NOT NULL,
    contribution_type          VARCHAR(255)   NOT NULL,
    contribution_percentage    DECIMAL(19, 2),
    contribution_decrease_rate DECIMAL(19, 2),
    contribution_threshold     DECIMAL(19, 2),
    win_chance_type            VARCHAR(255)   NOT NULL,
    win_chance_percentage      DECIMAL(19, 2),
    win_chance_initial_chance  DECIMAL(19, 2),
    win_chance_limit           DECIMAL(19, 2),
    win_chance_increase_rate   DECIMAL(19, 2)
);

CREATE TABLE bets
(
    bet_id       VARCHAR(36) PRIMARY KEY,
    user_id      VARCHAR(36)      NOT NULL,
    jackpot_id   VARCHAR(36)      NOT NULL,
    bet_amount   DECIMAL(19, 2)   NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (jackpot_id) REFERENCES jackpots (id)
);

CREATE TABLE jackpot_contributions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id              VARCHAR(36)      NOT NULL,
    user_id             VARCHAR(36)      NOT NULL,
    jackpot_id          VARCHAR(36)      NOT NULL,
    stake_amount        DECIMAL(19, 2)   NOT NULL,
    contribution_amount DECIMAL(19, 2)   NOT NULL,
    current_jackpot_amount DECIMAL(19, 2) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (bet_id),
    FOREIGN KEY (bet_id) REFERENCES bets (bet_id),
    FOREIGN KEY (jackpot_id) REFERENCES jackpots (id)
);

CREATE TABLE jackpot_rewards
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id              VARCHAR(36)      NOT NULL,
    user_id             VARCHAR(36)      NOT NULL,
    jackpot_id          VARCHAR(36)      NOT NULL,
    jackpot_reward_amount DECIMAL(19, 2) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (bet_id),
    FOREIGN KEY (bet_id) REFERENCES bets (bet_id),
    FOREIGN KEY (jackpot_id) REFERENCES jackpots (id)
);

CREATE TABLE outbox_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id       VARCHAR(36)      NOT NULL,
    user_id      VARCHAR(36)      NOT NULL,
    jackpot_id   VARCHAR(36)      NOT NULL,
    bet_amount   DECIMAL(19, 2)   NOT NULL,
    topic        VARCHAR(255)     NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (bet_id),
    FOREIGN KEY (jackpot_id) REFERENCES jackpots (id)
);

-- Initial data for jackpots
INSERT INTO jackpots (id, initial_pool, current_pool, contribution_type, contribution_percentage, win_chance_type, win_chance_percentage)
VALUES ('8d75dbf1-e50e-42f5-91b6-829c10f0d275', 1000.00, 1000.00, 'FIXED_CONTRIBUTION', 0.05, 'FIXED_CHANCE', 0.01);

INSERT INTO jackpots (id, initial_pool, current_pool, contribution_type, contribution_percentage, contribution_decrease_rate, contribution_threshold, win_chance_type, win_chance_initial_chance, win_chance_limit, win_chance_increase_rate)
VALUES ('fab085d6-4f0b-47ec-ac7a-5a7293d0d48f', 500.00, 500.00, 'VARIABLE_CONTRIBUTION', 0.10, 0.01, 10000.00, 'VARIABLE_CHANCE', 0.01, 10000.00, 0.1);